server:
  port: 8080
spring:
  application:
    name: "PragmaJava"
  devtools:
    add-properties: false
  profiles:
    include: null
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:postgres}:${POSTGRES_PORT:5432}/${POSTGRES_DB:pragmadb}
    username: ${POSTGRES_USER:pragmauser}
    password: ${POSTGRES_PASSWORD:password}
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    url: jdbc:postgresql://${POSTGRES_HOST:postgres}:${POSTGRES_PORT:5432}/${POSTGRES_DB:pragmadb}
    user: ${POSTGRES_USER:pragmauser}
    password: ${POSTGRES_PASSWORD:password}
    schemas: public
    baseline-on-migrate: true  # useful if db already has tables
    locations: classpath:db/migration
    driver-class-name: org.postgresql.Driver
  config:
    import: optional:configserver:http://localhost:8888
adapters:
  r2dbc:
    host: ${POSTGRES_HOST:postgres}
    port: ${POSTGRES_PORT:5432}
    database: ${POSTGRES_DB:pragmadb}
    schema: public
    username: ${POSTGRES_USER:pragmauser}
    password: ${POSTGRES_PASSWORD:password}
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"

eureka:
  instance:
    hostname: localhost
  client:
      service-url:
        defaultZone: http://localhost:8761/eureka/